test_task:
  matrix:
    - container:
        image: rust:latest
    - allow_failures: true
      container:
        image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    
  build_script: 
                          - /proc/cpuinfo
                          - /proc/meminfo
                         - cargo build
              
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index.
